# for Dataset
VIDEO_PATH="Video_Dataset"
RESHAPED_VIDEO_SIZE=128
PADDING_FRAME_SIZE=16
CROP_FRAME_SIZE=10
LABEL_SIZE=10
PATCH_SIZE=8
BATCH_SIZE=10
TEST_SIZE=0.2
VALID_SIZE=0.2

# Bool
PADDING=True
CROP=False
LOAD_CHECKPOINT=False
PREDICTION=True

# for Model
HIDDEN_DIM_VAE=256
EMBED_DIM_DIT=256
HIDDEN_DIM_DIT=512
DIT_INPUT_DIM=HIDDEN_DIM_VAE*PATCH_SIZE*PATCH_SIZE
DK_MODEL=64
CHANNEL_SIZE=3
N_TIMES=4
LR=0.0001
EPOCH=5

# For training
BETA_START=1e-4
BETA_END=0.02
N_TIMESTEPS=1000
CHECKPOINT_DIR="Latte_checkpoints.pth.tar"